### PR TITLE
fix(runtime): Set Content-Type header for stream routes

### LINKED ISSUE #179: router.stream() should set Content-Type: application/octet-stream header
## Description

The `router.stream()` helper in `@agentuity/runtime` does not set a `Content-Type` header on streaming responses. This causes the `useAPI` hook from `@agentuity/react` to not detect the response as a stream.

## Problem

In `packages/runtime/src/router.ts` (~line 490), `honoStream()` is called without setting any Content-Type header:

```typescript
return honoStream(c, async (s: any) => {
  // ...
});
```

The `useAPI` hook in `packages/react/src/api.ts` (lines 521-524) checks for specific content types to enable streaming:

```typescript
if (
  contentType.includes('text/event-stream') ||
  contentType.includes('application/octet-stream')
) {
  // Handle as stream...
}
```

Without the header, streaming responses fall through to regular JSON/text parsing, breaking real-time streaming on the client.

## Expected Behavior

`router.stream()` should set `Content-Type: application/octet-stream` before calling `honoStream()`.

## Suggested Fix

```typescript
const wrapper = (c: Context) => {
  const asyncLocalStorage = getAgentAsyncLocalStorage();
  const capturedContext = asyncLocalStorage.getStore();

  // Add this line:
  c.header('Content-Type', 'application/octet-stream');

  return honoStream(c, async (s: any) => {
    // ...
  });
};
```

### PR DESCRIPTION
**Pull request by rblalock**
## Summary

`router.stream()` now sets `Content-Type: application/octet-stream` header before calling `honoStream()`. This allows client-side hooks like `useAPI` to detect streaming responses and handle them correctly.

## Problem

Without this header, the `useAPI` hook in `@agentuity/react` (lines 521-524 of `api.ts`) checks for specific content types to enable streaming:

```typescript
if (
  contentType.includes('text/event-stream') ||
  contentType.includes('application/octet-stream')
) {
  // Handle as stream...
}
```

When no Content-Type is set, streaming responses fall through to regular JSON/text parsing which waits for the entire response before processing - breaking real-time streaming on the client.

## Solution

Add `c.header('Content-Type', 'application/octet-stream')` before calling `honoStream()` in the `router.stream()` wrapper.

## Testing

Tested with air-new project - streaming now works correctly with tokens arriving incrementally.

Fixes #179

## Summary by CodeRabbit

* **Bug Fixes**
  * Streaming responses now include proper content-type headers for improved client detection and compatibility.

* **Chores**
  * Removed legacy phase-based plugin configuration from test fixtures.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: packages/runtime/src/router.ts [hunk 1]
```diff
@@ -487,6 +487,9 @@ export const createRouter = <E extends Env = Env, S extends Schema = Schema>():
 			const asyncLocalStorage = getAgentAsyncLocalStorage();
 			const capturedContext = asyncLocalStorage.getStore();
 
+			// Set Content-Type header for streaming response detection by clients
+			c.header('Content-Type', 'application/octet-stream');
```
Comment (jhaynie) [inline packages/runtime/src/router.ts]: good enough to unblock this but we probably want to follow-up and look at the schema to determine the content-type too.
